name: Gemini CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Cloud Credentials
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" > gcp-key.json

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=gcp-key.json

      - name: Run gemini.py
        run: python gemini.py
